repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: end-of-file-fixer
      - id: flake8
        args: [--max-line-length=120]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: run_tests.sh
        language: script
        types: [python]
  - repo: local
    hooks:
      - id: radon
        name: radon
        entry: run_radon.sh
        language: script
        types: [python]
