respos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: end-of-file-fixer
      - id: flake8
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: run_tests.sh
        language: script
        type: [python]
